/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JTablaEventos.java
 *
 * Created on 20/10/2011, 07:28:25 PM
 */

package ejemplopuertoserie;


import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.SerialPortEvent;

/**
 *
 * @author MUNOZ
 */
public class JTablaEventos extends javax.swing.JFrame {
    private SerialPortManagement serialPortManagement;
    private String initialDate;
    private String finalDate;

    /** Creates new form JTablaEventos */
    public JTablaEventos(SerialPortManagement serialPortManagement,String initialDate,String finalDate) {
        this.serialPortManagement = serialPortManagement;
        this.initialDate=initialDate;
        this.finalDate=finalDate;
        initComponents();
        configureTableModel();
        setLocationRelativeTo(null);
    }

    public TableModel configureTableModel(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        List<SerialPortEvent> list= serialPortManagement.getPersistance().getEvents(initialDate,finalDate);
        Object[][] object = new Object[list.size()][5];
        Object[] names = new Object[]{"Nombre del Evento","Tipo de Terminal",
        "Origen del Evento","Fecha","Ubicacion"};
        for(int i=0;i<list.size();i++){
                object[i][0] = list.get(i).getName();
                object[i][1] = list.get(i).getTerminalType();
                object[i][2] = list.get(i).getEventOrigen();
                object[i][3] = list.get(i).getStringDate();
                object[i][4] = list.get(i).getLocation();
                /*tableModel.setValueAt(list.get(i).getName(), i, 0);
                tableModel.setValueAt(list.get(i).getValue(), i, 1);
                tableModel.setValueAt(list.get(i).getDate(), i, 2);
                tableModel.setValueAt(list.get(i).getLocation(), i, 3);
                tableModel.setValueAt(list.get(i).getTerminalType(), i, 4);*/

        }
        return new DefaultTableModel(object, names);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Eventos Antiguos");

        jTable1.setModel(configureTableModel());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTablaEventos().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
